{{ if .Values.ingestion.enabled }}
{{ if not .Values.ingestion.collections.configMap }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-operator
  labels:
    app: config-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-operator
  template:
    metadata:
      labels:
        app: config-operator
    spec:
      serviceAccountName: config-operator
      containers:
        - name: config-operator
          image: {{ .Values.ingestion.configOperator.image }}
          imagePullPolicy: Always
      tolerations:
        - key: "sdap-role"
          operator: "Equal"
          value: "driver"
          effect: "NoSchedule"
      nodeSelector:
        sdap-role: driver
{{ end }}
{{ end }}
